"""Add PvP match models

Revision ID: 168989cbaec8
Revises:
Create Date: 2026-02-02 20:23:23.439635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '168989cbaec8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('hints', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_difficulty'), 'tasks', ['difficulty'], unique=False)
    op.create_index(op.f('ix_tasks_subject'), 'tasks', ['subject'], unique=False)
    op.create_index('ix_tasks_subject_difficulty', 'tasks', ['subject', 'difficulty'], unique=False)
    op.create_index(op.f('ix_tasks_topic'), 'tasks', ['topic'], unique=False)
    op.create_index('ix_tasks_topic_difficulty', 'tasks', ['topic', 'difficulty'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('role', sa.String(), server_default='user', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('matches',
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'ACTIVE', 'FINISHED', 'CANCELLED', 'ERROR', name='matchstatus', native_enum=False), server_default='waiting', nullable=False),
    sa.Column('player1_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('player2_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('rating_change', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_player1_id'), 'matches', ['player1_id'], unique=False)
    op.create_index(op.f('ix_matches_player2_id'), 'matches', ['player2_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_type'), 'user_achievements', ['type'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_index('ix_user_achievements_user_type', 'user_achievements', ['user_id', 'type'], unique=True)
    op.create_table('user_task_attempts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_task_attempts_is_correct'), 'user_task_attempts', ['is_correct'], unique=False)
    op.create_index(op.f('ix_user_task_attempts_task_id'), 'user_task_attempts', ['task_id'], unique=False)
    op.create_index('ix_user_task_attempts_user_correct', 'user_task_attempts', ['user_id', 'is_correct'], unique=False)
    op.create_index('ix_user_task_attempts_user_created', 'user_task_attempts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_task_attempts_user_id'), 'user_task_attempts', ['user_id'], unique=False)
    op.create_index('ix_user_task_attempts_user_task', 'user_task_attempts', ['user_id', 'task_id'], unique=False)
    op.create_table('match_answers',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_answers_match_id'), 'match_answers', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_answers_task_id'), 'match_answers', ['task_id'], unique=False)
    op.create_index('ix_match_answers_unique_submission', 'match_answers', ['match_id', 'user_id', 'task_id'], unique=True)
    op.create_index(op.f('ix_match_answers_user_id'), 'match_answers', ['user_id'], unique=False)
    op.create_table('match_tasks',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_tasks_match_id'), 'match_tasks', ['match_id'], unique=False)
    op.create_index('ix_match_tasks_match_order', 'match_tasks', ['match_id', 'order'], unique=False)
    op.create_index(op.f('ix_match_tasks_task_id'), 'match_tasks', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_tasks_task_id'), table_name='match_tasks')
    op.drop_index('ix_match_tasks_match_order', table_name='match_tasks')
    op.drop_index(op.f('ix_match_tasks_match_id'), table_name='match_tasks')
    op.drop_table('match_tasks')
    op.drop_index(op.f('ix_match_answers_user_id'), table_name='match_answers')
    op.drop_index('ix_match_answers_unique_submission', table_name='match_answers')
    op.drop_index(op.f('ix_match_answers_task_id'), table_name='match_answers')
    op.drop_index(op.f('ix_match_answers_match_id'), table_name='match_answers')
    op.drop_table('match_answers')
    op.drop_index('ix_user_task_attempts_user_task', table_name='user_task_attempts')
    op.drop_index(op.f('ix_user_task_attempts_user_id'), table_name='user_task_attempts')
    op.drop_index('ix_user_task_attempts_user_created', table_name='user_task_attempts')
    op.drop_index('ix_user_task_attempts_user_correct', table_name='user_task_attempts')
    op.drop_index(op.f('ix_user_task_attempts_task_id'), table_name='user_task_attempts')
    op.drop_index(op.f('ix_user_task_attempts_is_correct'), table_name='user_task_attempts')
    op.drop_table('user_task_attempts')
    op.drop_index('ix_user_achievements_user_type', table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_type'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_player2_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_player1_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_tasks_topic_difficulty', table_name='tasks')
    op.drop_index(op.f('ix_tasks_topic'), table_name='tasks')
    op.drop_index('ix_tasks_subject_difficulty', table_name='tasks')
    op.drop_index(op.f('ix_tasks_subject'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_difficulty'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
